PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Rekha E Store','rekha-e-store-akola','E-commerce','Akola',1,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Ambhore Guruji Sahityalay','ambhore-guruji-sahityalay-washim','Book Store','Washim',2,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('AI Lab','ai-lab-akola','Technology & Software','Akola',3,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Apaji Industries Pvt. Ltd.','apaji-industries-pvt-ltd-vyala-akola','Contractor','Vyala, Akola',4,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('M/s Shree Samarth Labour Suppliers and Contractor','m-s-shree-samarth-labour-suppliers-and-contractor-akola','Contractor','Akola',5,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Piyush Academy','piyush-academy-akola','Education','Akola',6,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Deva Mart','deva-mart-akola','Retail','Akola',7,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Dharamaji Gharde Bahuddeshiy Seva Sanstha','dharamaji-gharde-bahuddeshiy-seva-sanstha-akola','Manpower','Akola',8,1,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Dr Babasaheb Ambedkar Centre for Excellence and Research','dr-babasaheb-ambedkar-centre-for-excellence-and-research-akola','Education','Akola',9,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Seva Bahuuddeshiya Sanstha Washim','seva-bahuuddeshiya-sanstha-washim-washim','Trust','Washim',10,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Seva Bahuuddeshiya Sanstha Washim','seva-bahuuddeshiya-sanstha-washim-akola','Contractor','Akola',11,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Feel Secure','feel-secure-akola','CCTV & Security','Akola',12,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('PWD Contractor','pwd-contractor-chandrapur','Contractor','Chandrapur',13,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Gargi Enterprises','gargi-enterprises-akola','Contractor','Akola',14,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Proxy Flooring and Coating Business','proxy-flooring-and-coating-business-akola','Contractor','Akola',15,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Golden Rize Private Limited','golden-rize-private-limited-washim','Company','Washim',16,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('NGO','ngo-akola','NGO','Akola',17,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Kamal Trading Company','kamal-trading-company-washim','Importer','Washim',18,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Amrita Prashant Kasbe','amrita-prashant-kasbe-thane-mumbai','Professional Services','Thane, Mumbai',19,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Shourya Kirana Shop','shourya-kirana-shop-akola','Kirana Shop','Akola',20,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Krushi Padhidahark Bahuddeshiy Sanstha','krushi-padhidahark-bahuddeshiy-sanstha-akola','NGO','Akola',21,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Dorvelo','dorvelo-mumbai','E-commerce','Mumbai',22,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Maitriya Seva','maitriya-seva-akola','NGO','Akola',23,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Neeltech Forecasting Private Limited','neeltech-forecasting-private-limited-akola','Private Limited Company','Akola',24,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Neha Xerox','neha-xerox-malegaon','Xerox Shop','Malegaon',25,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Devansh Agro Agency','devansh-agro-agency-shirpur-malegaon','Agro Agency','Shirpur, Malegaon',26,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Sudantya Pvt. Ltd.','sudantya-pvt-ltd-nagpur','Private Limited Company','Nagpur',27,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('PH Tech Industrial Solutions','ph-tech-industrial-solutions-nagpur','Industrial Shop','Nagpur',28,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Shree Vitthal Multiservice','shree-vitthal-multiservice-akola','Manpower Agency','Akola',29,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Tathagat Enterprises','tathagat-enterprises-aurangabad','Medical','Aurangabad',30,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Riya Enterprises','riya-enterprises-washim','Battery Manufacturing','Washim',31,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Contractor','contractor-akola','Contractor','Akola',32,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Sevarth Global Health Care Service','sevarth-global-health-care-service-washim','Laboratory','Washim',33,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Yogiraj Enterprises','yogiraj-enterprises-akola','Manpower Agency','Akola',34,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Orange City Human Recruiter','orange-city-human-recruiter-nagpur','HR Recruitment Agency','Nagpur',35,0,1);
INSERT OR IGNORE INTO clients(company_name,slug,nature_of_business,city,display_order,is_featured,is_published) VALUES('Sid Construction','sid-construction-akola','Contractor','Akola',36,0,1);
INSERT OR IGNORE INTO services(service_name,slug) VALUES('GST Registration','gst-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Tender Services','tender-services');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Maharashtra Labour Welfare Board Registration','maharashtra-labour-welfare-board-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('ISO Certification','iso-certification');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('MSME/Udyam Registration','msme-udyam-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Licence Services','licence-services');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('GeM Registration','gem-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Digital Signature Certificate','digital-signature-certificate');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Partnership Firm Registration','partnership-firm-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Company Registration','company-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Trademark Registration','trademark-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Food Licence','food-licence');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Shop Act Registration','shop-act-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Income Tax Return Filing','income-tax-return-filing');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Provident Fund Registration','provident-fund-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('ESIC Registration','esic-registration');
INSERT OR IGNORE INTO services(service_name,slug) VALUES('Contractor Licence','contractor-licence');
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Rekha E Store') AND lower(c.city)=lower('Akola') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Ambhore Guruji Sahityalay') AND lower(c.city)=lower('Washim') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('AI Lab') AND lower(c.city)=lower('Akola') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Apaji Industries Pvt. Ltd.') AND lower(c.city)=lower('Vyala, Akola') AND s.slug='tender-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('M/s Shree Samarth Labour Suppliers and Contractor') AND lower(c.city)=lower('Akola') AND s.slug='maharashtra-labour-welfare-board-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('M/s Shree Samarth Labour Suppliers and Contractor') AND lower(c.city)=lower('Akola') AND s.slug='tender-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Piyush Academy') AND lower(c.city)=lower('Akola') AND s.slug='iso-certification';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Deva Mart') AND lower(c.city)=lower('Akola') AND s.slug='msme-udyam-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Dharamaji Gharde Bahuddeshiy Seva Sanstha') AND lower(c.city)=lower('Akola') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Dr Babasaheb Ambedkar Centre for Excellence and Research') AND lower(c.city)=lower('Akola') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Seva Bahuuddeshiya Sanstha Washim') AND lower(c.city)=lower('Washim') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Feel Secure') AND lower(c.city)=lower('Akola') AND s.slug='gem-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('PWD Contractor') AND lower(c.city)=lower('Chandrapur') AND s.slug='digital-signature-certificate';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Gargi Enterprises') AND lower(c.city)=lower('Akola') AND s.slug='partnership-firm-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Proxy Flooring and Coating Business') AND lower(c.city)=lower('Akola') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Golden Rize Private Limited') AND lower(c.city)=lower('Washim') AND s.slug='company-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('NGO') AND lower(c.city)=lower('Akola') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('NGO') AND lower(c.city)=lower('Akola') AND s.slug='tender-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Kamal Trading Company') AND lower(c.city)=lower('Washim') AND s.slug='tender-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Amrita Prashant Kasbe') AND lower(c.city)=lower('Thane, Mumbai') AND s.slug='trademark-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Shourya Kirana Shop') AND lower(c.city)=lower('Akola') AND s.slug='food-licence';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Krushi Padhidahark Bahuddeshiy Sanstha') AND lower(c.city)=lower('Akola') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Dorvelo') AND lower(c.city)=lower('Mumbai') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Dorvelo') AND lower(c.city)=lower('Mumbai') AND s.slug='msme-udyam-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Dorvelo') AND lower(c.city)=lower('Mumbai') AND s.slug='shop-act-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Neha Xerox') AND lower(c.city)=lower('Malegaon') AND s.slug='income-tax-return-filing';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Devansh Agro Agency') AND lower(c.city)=lower('Shirpur, Malegaon') AND s.slug='shop-act-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Sudantya Pvt. Ltd.') AND lower(c.city)=lower('Nagpur') AND s.slug='company-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('PH Tech Industrial Solutions') AND lower(c.city)=lower('Nagpur') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('PH Tech Industrial Solutions') AND lower(c.city)=lower('Nagpur') AND s.slug='msme-udyam-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('PH Tech Industrial Solutions') AND lower(c.city)=lower('Nagpur') AND s.slug='shop-act-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Shree Vitthal Multiservice') AND lower(c.city)=lower('Akola') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Tathagat Enterprises') AND lower(c.city)=lower('Aurangabad') AND s.slug='licence-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Tathagat Enterprises') AND lower(c.city)=lower('Aurangabad') AND s.slug='gem-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Riya Enterprises') AND lower(c.city)=lower('Washim') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Riya Enterprises') AND lower(c.city)=lower('Washim') AND s.slug='msme-udyam-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Riya Enterprises') AND lower(c.city)=lower('Washim') AND s.slug='shop-act-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Contractor') AND lower(c.city)=lower('Akola') AND s.slug='gst-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Contractor') AND lower(c.city)=lower('Akola') AND s.slug='msme-udyam-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Contractor') AND lower(c.city)=lower('Akola') AND s.slug='shop-act-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Contractor') AND lower(c.city)=lower('Akola') AND s.slug='maharashtra-labour-welfare-board-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Contractor') AND lower(c.city)=lower('Akola') AND s.slug='tender-services';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Sevarth Global Health Care Service') AND lower(c.city)=lower('Washim') AND s.slug='msme-udyam-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Yogiraj Enterprises') AND lower(c.city)=lower('Akola') AND s.slug='provident-fund-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Yogiraj Enterprises') AND lower(c.city)=lower('Akola') AND s.slug='esic-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Yogiraj Enterprises') AND lower(c.city)=lower('Akola') AND s.slug='maharashtra-labour-welfare-board-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Yogiraj Enterprises') AND lower(c.city)=lower('Akola') AND s.slug='iso-certification';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Orange City Human Recruiter') AND lower(c.city)=lower('Nagpur') AND s.slug='shop-act-registration';
INSERT OR IGNORE INTO client_services(client_id,service_id) SELECT c.id,s.id FROM clients c,services s WHERE lower(c.company_name)=lower('Sid Construction') AND lower(c.city)=lower('Akola') AND s.slug='contractor-licence';
COMMIT;
